name: FreezingWand
version: '${project.version}'
main: com.ashkiano.freezingwand.FreezingWand
api-version: '1.16'
author: AshKiano
commands:
  freezingwand:
    description: Gives the player a freezing wand.